name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"] # Pastikan ini sesuai dengan branch utama kamu
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job untuk Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Ganti ke 'yarn' atau 'pnpm' jika kamu tidak pakai npm

      - name: Install dependencies
        run: npm ci # Menggunakan ci agar instalasi lebih bersih dan cepat di CI/CD

      - name: Build Project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Mengarahkan artifact ke folder hasil build React
          # JIKA PAKAI VITE: ganti menjadi './dist'
          # JIKA PAKAI CREATE REACT APP: tetap './build'
          path: './dist' 

  # Job untuk Deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
